### ISSUE TITLE
Error when specifying socket_timeout

### ISSUE THREAD

**Issue by bitroost** [gjr80/weewx-gw1000#28]
Python 3.7.3 / weewx v4.4.0

When using socket_timeout, e.g.

```
[GW1000]
    driver = user.gw1000
    ip_address = XX.XX.XX.XX
    port = 45000
    poll_interval = 30
    socket_timeout = 5
    max_tries = 3
    retry_wait = 10
```

in the config of the driver in weewx.conf, the driver fails to load

`Mar 24 15:56:32 rsp1 weewx[28170] DEBUG user.gw1000: Failed attempt 1 to send command 'CMD_READ_STATION_MAC': an integer is required (got type str            )`

it seems that `self.socket_timeout` arrives as string @ `gw1000.py line 3361`:
`socket_obj.settimeout(self.socket_timeout)`

**Comment by gjr80** [comment]
Thanks, I missed converting `socket_timeout` and `broadcast_port` to integers when read from `weewx.conf` which is why the defaults work fine. Fixed at commit 09286592130380442a656897e8407cd6ac7d5388, will appear a v0.3.1 in few days. In the meantime if your require the v0.3.1 code with the fix you can download `gw1000.py` using:
```
$ wget https://raw.githubusercontent.com/gjr80/weewx-gw1000/master/bin/user/gw1000.py
```
then just copy it over your v0.3.0 `gw1000.py`. You will need to restart WeeWX for the change to take effect.
