### ISSUE TITLE
Ambient PM25IN AQ sensor

### ISSUE THREAD

**Issue by rlmalisz** [gjr80/weewx-gw1000#34]
I am new to WeeWX, so sorry if this is a stupid question.  I have the sensor in the title.  The GW1000 is clearly picking up data from it, and from code in your driver and in the Accumulators section in weewx.conf, I would expect it to be showing up.  Any suggestion on where I am missing the boat for this would be much appreciated!

--Richard

PS: we also have a Purple Air outdoor sensor, which I hope to add via a separate extension.  So having the PM25IN show up as indoor would be much desired.

**Comment by gjr80** [comment]
Hi, I'm sorry but I am not familiar with that sensor, no matter, you say '_the GW1000 is clearly picking up data from it_'. I presume that means you are seeing it's data appear somewhere; are you seeing data from the sensor in the WS View app, in the output of the GW1000 driver when you run the driver directly (refer step 5 of the [Installation as a WeeWX driver](https://github.com/gjr80/weewx-gw1000#installation-as-a-weewx-driver) section of the readme) or in the loop packets and archive records visible when [WeeWX is run directly](http://weewx.com/docs/usersguide.htm#Running_directly)? 

Depending on what you do/do not see will depend on what you need to do to track down the issue.

Gary

**Comment by rlmalisz** [comment]
Yes, I was seeing the data in the Ws View app, and yes, the driver puts out values for pm2_5 and pm2_51_24h_avg, which I assumed were bound for WeeWX.  The value I'm interested in from this thing is the pm2_5.  Your install doesn't add an accumulaor entry in weewx.conf for that value, so presumably it was falling on the floor?  I added the accumulator entry, doctored up current.inc, and am now seeing current values show up in the HTML.

**Comment by gjr80** [comment]
There is a very good reason why there is no `[Accumulator]` entry for `pm2_5` in `weewx.conf` and that is because those `[Accumulator]` entries define the extractor function that WeeWX uses to extract that particular field value from the Accumulator, the default function is `average` which gives the average value, the entries the driver installation puts in the `[Accumulator]` stanza are for those fields that need to use a different extractor function, typically `last`. Simply put, the extractor function required by `pm2_5` is the default extractor function so there is no need to specify it.
In any case whether there is an extractor entry for a field in `[Accumulator]` makes no difference as to whether WeeWX accumulates a field or not as WeeWX accumulates all numeric fields contained in loop packets from the driver, they do not ‘fall on the floor’. Similarly they are automatically extracted when WeeWX synthesises an archive record, it is just the extractor function we change.
I suspect that your system was always accumulating `pm2_5` and including `pm2_5` in archive records but it was the lack of the necessary code in `current.inc` that prevented display of `pm2_5`. Did you ever [run WeeWX directly](http://weewx.com/docs/usersguide.htm#Running_directly) to see if `pm2_5` was included in loop packets as archive records? If it was then the driver and accumulators are working as they should.

**Comment by gjr80** [comment]
Closing due to lack of a response. Can be re-opened if required.
