### ISSUE TITLE
Testing the driver with errors

### ISSUE THREAD

**Issue by lemuba** [gjr80/weewx-gw1000#4]
root@DietPi:~# sudo /home/weewx/bin/wee_extension --install=/var/tmp/gw1000-0.1.0b5.tar.gz
Request to install '/var/tmp/gw1000-0.1.0b5.tar.gz'
Extracting from tar archive /var/tmp/gw1000-0.1.0b5.tar.gz
Saving installer file to /home/weewx/bin/user/installer/GW1000
Saved configuration dictionary. Backup copy at /home/weewx/weewx.conf.20200724165212
Finished installing extension '/var/tmp/gw1000-0.1.0b5.tar.gz'
root@DietPi:~# PYTHONPATH=/home/weewx/bin python -m user.gw1000 --test-driver
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/weewx/bin/user/gw1000.py", line 267, in <module>
    import weecfg
  File "/home/weewx/bin/weecfg/__init__.py", line 22, in <module>
    import configobj
ImportError: No module named configobj
root@DietPi:~# 

by the way, many thanks for this driver! - I hope to get it running because I´m not happy with the interceptor limitations...

**Comment by lemuba** [comment]
Got it running by running Python 3.5 as default this way:

https://raspberry-valley.azurewebsites.net/Python-Default-Version/

**Comment by gjr80** [comment]
I appreciate a solution has been found, in this case changing the default python version that is run when the command `python` is executed. Another solution is to explicitly specify the python version in the command, eg:
```
$ PYTHONPATH=/home/weewx/bin python3 -m user.gw1000 --test-driver
```

I expect this problem will come up more regularly since WeeWX 4.x can be installed and run under python2 or python3. I will add some further explanatory comments in the comments and documents where running the driver directly is mentioned, in fact it should also be possible to catch the import error and suggest the user check their python version.

**Comment by gjr80** [comment]
Added note about specifying python version to each place where I have found instructions on how to run the driver directly.

Unfortunately I am unable to trap the import/module not found errors so that i can warn the user of the problem.
