### ISSUE TITLE
Missing wiki pages

### ISSUE THREAD

**Issue by cliffordsnow** [gjr80/weewx-gw1000#45]
I just started using the weewx and your gw1000 device driver. I'm missing barometer and pm25 readings. Looking at the [wiki] (https://github.com/gjr80/weewx-gw1000/wiki/Available-config-options)], pages field_map and field_map_extension are missing. Do you have a copy of them available?

**Comment by gjr80** [comment]
There are no field_map and field_map_extensions wiki pages as such (there is a [Field map](https://github.com/gjr80/weewx-gw1000/wiki/Field-map) page but that page covers field maps in general rather than the [[field_map]] and [[field_map_extensions]] stanzas specifically).  What looks like dead links on that page are in fact just mentions of the [[field_map]] and [[field_map_extensions]] stanzas. This is a limitation in the GitHub markdown implementation whereby double, triple etc square bracketed text is treated as a link. This causes problems when you want to include configobj style stanza headings that use one or more square brackets for hierarchy. 

I have reformatted the page to use code blocks for the GW1000 config options and config stanzas. Unfortunately my development environment displays the markdown correctly so occasionally pages slip past that have the malformed formatting.  Thanks for pointing this out.
